name: exercise4

on:
    schedule:
     - cron: '* * * * *'      

jobs:
    exercise3:
        runs-on: ubuntu-latest
        steps:
            - name: greeting
              run: echo "thanks for the time zone"