name: exercise3

on:
    push:
        branches:
            - practise
jobs:
    exercise3:
        runs-on: ubuntu-latest
        steps:
            - name: greeting
              run: echo "hello how are you"
            - name: ping test
              run: ping -c 4 google.com